protocol :
	pandoc Omnibus_F15_Protocol.md -s -o Exported/Omnibus_F15_Protocol.pdf --toc -V title=Fall\ 2015\ Omnibus\ Protocol

Omni.F14.protocol :
	pandoc omni.F14.protocol.md -s -o Exported/Omnibus_F14_Protocol.pdf --toc -V title=Fall\ 2014\ Omnibus\ Protocol

biopac.manual :
	pandoc BIOPAC.manual.md -s -o Exported/BIOPAC.manual.pdf --toc -V title=BIOPAC\ Manual
